// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0B7dezxphrtoZIraC17WF6iB02jy-dGw',
    appId: '1:549368334683:android:3143c81ea2ce8ac8dd327e',
    messagingSenderId: '549368334683',
    projectId: 'flutter-54aac',
    storageBucket: 'flutter-54aac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Yd_WFJVyvAG_HNnMANF2_d-IFWO1Vm0',
    appId: '1:549368334683:ios:5c419e5b9c0c84fedd327e',
    messagingSenderId: '549368334683',
    projectId: 'flutter-54aac',
    storageBucket: 'flutter-54aac.firebasestorage.app',
    iosBundleId: 'com.example.aiChatRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Yd_WFJVyvAG_HNnMANF2_d-IFWO1Vm0',
    appId: '1:549368334683:ios:6887e10bbf3c66fadd327e',
    messagingSenderId: '549368334683',
    projectId: 'flutter-54aac',
    storageBucket: 'flutter-54aac.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
